tasks:
  - init: whoami && sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 && sudo chmod a+x /usr/local/bin/yq
  - init : whoami && sudo chmod a+w  ./experimental_docker_compose_files/02_custom_docker_file_connecting_agent_and_controller/dockerfiles
  - init : whoami && yq && sh ./experimental_docker_compose_files/02_custom_docker_file_connecting_agent_and_controller/gitpodURL.sh
