services:
  jenkins_controller: 
    image: jenkins/jenkins:2.401.1-lts
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    
  jenkins_agent:
    image: jenkins/ssh-agent:5.3.0-jdk11
    container_name: agent
    privileged: true
    user: root
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINVxUeiHKOsQBml4gDe4cAd8KGK4TZzYJGmqPDZgI6aE jh@jh-Modern-14-B5M
volumes: 
  jenkins_home: 
